version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/nds2018
hooks:
 BeforeInstall:
    - location: scripts/clear.sh
      timeout: 90
      runas: root
  AfterInstall:
    - location: scripts/rsync.sh
      timeout: 90
      runas: root
