version: 0.0
os: linux 
files:
  - source: /
    destination: /tmp/deploy-current/
hooks:
#  BeforeInstall:
#    - location: scripts/clear.sh
#      timeout: 90
 #     runas: root
  AfterInstall:
    - location: scripts/rsync.sh
      timeout: 90
      runas: root
